# Generated by Django 3.2.16 on 2023-03-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esdtest',
            name='image',
            field=models.ImageField(blank=True, upload_to='test_image'),
        ),
    ]
