# Generated by Django 3.2.16 on 2023-02-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tab_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
